package main

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	// _ "./docs" // docs is generated by Swag CLI, you have to import it.
)

// @title Swagger Example API
// @version 1.0
// @description This is a sample server Petstore server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host 127.0.0.1:8080
// @BasePath /v1

func main() {
	r := gin.Default()

	r.GET("/ping", APIPing)
	r.GET("/hello/:name", APIHello)
	r.GET("/param", APIParam)

	r.Run(":8888") // listen and serve on 0.0.0.0:8080
}

func (m *MessageInfo) RespMessage() MessageInfo {
	return MessageInfo{
		Message: m.Message,
	}
}

type MessageInfo struct {
	Message string `json:"messge"`
}

type ParamList struct {
	Name string `form:"name" binding:"required"`
	Age  string `form:"age" binding:"required"`
}

// APIPing get api ping
func APIPing(c *gin.Context) {
	messageinfo := MessageInfo{
		Message: "pong",
	}
	c.JSON(http.StatusOK, messageinfo.RespMessage())
}

func APIHello(c *gin.Context) {
	messageinfo := MessageInfo{
		Message: c.Param("name"),
	}
	c.JSON(http.StatusOK, messageinfo.RespMessage())
}

func APIParam(c *gin.Context) {
	var param ParamList
	if err := c.ShouldBindQuery(&param); err != nil {
		fmt.Println(err)
		return
	}
	messageinfo := MessageInfo{
		Message: fmt.Sprintf("name: %s , age: %s", param.Name, param.Age),
	}
	c.JSON(http.StatusOK, messageinfo.RespMessage())
}
